# Generated by Django 6.0.5 on 2026-05-19 04:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('district', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
            },
        ),
        migrations.CreateModel(
            name='RescueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team_type', models.CharField(choices=[('NDRF', 'NDRF - National Disaster Response Force'), ('SDRF', 'SDRF - State Disaster Response Force'), ('FIRE', 'Fire & Rescue Services'), ('COAST_GUARD', 'Coast Guard'), ('POLICE', 'Police Emergency'), ('HEALTH', 'Health & Medical'), ('CIVIL', 'Civil Defence'), ('NGO', 'NGO / Volunteer Group'), ('OTHER', 'Other')], max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('alternate_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('district', models.CharField(max_length=100)),
                ('base_location', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('personnel_count', models.IntegerField(default=0)),
                ('vehicles_available', models.IntegerField(default=0)),
                ('boats_available', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rescue Team',
                'verbose_name_plural': 'Rescue Teams',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('current_level_meters', models.FloatField(help_text='Water level in meters')),
                ('danger_level_meters', models.FloatField(help_text='Danger threshold in meters')),
                ('warning_level_meters', models.FloatField(help_text='Warning threshold in meters')),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WATCH', 'Watch'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Water Level Monitor',
                'verbose_name_plural': 'Water Level Monitors',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='FloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=200)),
                ('reporter_phone', models.CharField(max_length=20)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('water_level_estimate', models.CharField(blank=True, help_text='e.g. knee-deep, waist-deep, 2 feet', max_length=100)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CATASTROPHIC', 'Catastrophic')], default='MODERATE', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_notes', models.TextField(blank=True)),
                ('people_affected', models.IntegerField(default=0)),
                ('evacuation_needed', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('rescue_team_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rescueteam')),
            ],
            options={
                'verbose_name': 'Flood Report',
                'verbose_name_plural': 'Flood Reports',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('affected_area', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EXTREME', 'Extreme')], default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('water_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.waterlevel')),
            ],
            options={
                'verbose_name': 'Flood Alert',
                'verbose_name_plural': 'Flood Alerts',
                'ordering': ['-issued_at'],
            },
        ),
    ]
