# Generated by Django 4.2.29 on 2026-05-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_waterlevel_api_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodreport',
            name='water_level_estimate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='api_last_synced',
            field=models.DateTimeField(blank=True, help_text='Last weather API sync time', null=True),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='weather_description',
            field=models.CharField(blank=True, help_text='e.g. heavy rain', max_length=200),
        ),
    ]
